#!/usr/bin/env node

process.on("SIGINT", () => process.exit(1));
process.on("SIGTERM", () => process.exit(1));

const fs = require("fs/promises");
const path = require("path");
const dotenv = require("dotenv");
const pup = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');

dotenv.config({ path: path.resolve(__dirname, ".env") });

const YOUTUBE_EMAIL = process.env.YOUTUBE_EMAIL;
const YOUTUBE_PASSWORD = process.env.YOUTUBE_PASSWORD;

const missingEnvVars = ["YOUTUBE_EMAIL", "YOUTUBE_PASSWORD"].filter(
    (envVarName) => !process.env[envVarName]
);

if (missingEnvVars.length > 0) {
    console.error(
        `Missing required environment variable(s): ${missingEnvVars.join(", ")}. ` +
        `Please set them in automation/.env.`
    );
    process.exit(1);
}

// const url = 'https://bot.sannysoft.com';
const url = 'https://youtu.be/lHRFaMlMi6M?si=lMaDf4jrpunlT5cX';
const cookiesFilePath = './../cookies.txt';
const stealh = StealthPlugin();
stealh.enabledEvasions.delete('iframe.contentWindow');
stealh.enabledEvasions.delete('media.codecs');
pup.use(stealh);

function wait(time) {
    return new Promise(function (res) {
        setTimeout(res, time);
    });
}

function parseCookieDomain(domain) {
    if (domain.startsWith(".")) {
        return domain;
    }
    return `.${domain}`;
}


function parseCookieExpirationValue(expires) {
    let newValue = expires;

    if (expires == -1) {
        newValue = Date.now() + 365 * 86400 * 1000; // one year from now
    }

    return Math.round(newValue);
}


function parseCookieValue(value) {
    return value.trim();
}

function buildCookiesData(
    cookies
) {
    return cookies
        .sort(
            (
                cookieA,
                cookieB
            ) => {
                return cookieA.domain > cookieB.domain ? 1 : -1;
            }
        )
        .reduce(
            (data, cookie) => {
                const newRow = [
                    parseCookieDomain(cookie.domain),
                    "TRUE",
                    cookie.path,
                    cookie.secure,
                    parseCookieExpirationValue(cookie.expires),
                    cookie.name,
                    parseCookieValue(cookie.value),
                ];

                return `${data}\n${newRow.join("\t")}`;
            },
            "# Netscape HTTP Cookie File\n# This was generated by US Do not edit.\n\n"
        );
}

async function buildCookiesTxtAsync(
    cookies
) {
    const cookiesNetscapeFormat = buildCookiesData(cookies);
    await fs.writeFile(cookiesFilePath, cookiesNetscapeFormat);
    console.info(`Successfully written cookies to ${cookiesFilePath}`);
}

// Function to sign in to YouTube
async function signIn(page) {
    try {
        // Navigate to YouTube
        await page.goto('https://accounts.google.com/signin', { waitUntil: 'networkidle2', timeout: 10000 });
        // await page.goto('https://accounts.google.com/', { waitUntil: 'networkidle0', timeout: 1000 });

        console.log("acc page opened");
        // Click the Sign In button
        // await page.click('#signInButton');

        // Wait for the email field to be visible
        await page.waitForSelector('#identifierId');

        // Click on the email field
        await page.click('#identifierId');

        // Enter the email
        await page.type('#identifierId', YOUTUBE_EMAIL);

        // Click the Next button
        await Promise.all([
            page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 5000 }),
            page.click('#identifierNext button'),
        ]);

        // Wait for the password field to be visible
        await page.waitForSelector('input[type="password"]', { visible: true });

        // Enter the password
        await page.type('input[type="password"]', YOUTUBE_PASSWORD);

        page.waitForSelector("#passwordNext", { visible: true });

        // Click the Next button
        await Promise.all([
            page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 5000 }),
            page.click('#passwordNext button'),
        ]);

        console.log('Successfully signed in to YouTube');
    } catch (error) {
        console.error('Error signing in to YouTube', error);
    }
}

async function playVideo(page) {
    await p.goto(url);
    // await p.waitForTimeout(5000);

    await p.screenshot({ path: 'bot.jpg', fullPage: true });

    console.log("Video Page Opened");
    // await p.goto('https://youtu.be/lHRFaMlMi6M?si=lMaDf4jrpunlT5cX');
    const videoDuration = await p.$eval('video', (el) => el.duration);
    console.log("video duration " + videoDuration * 1000);
    await p.waitForSelector('.ytp-play-button');
    console.log("Play Button appeared");

    console.log("play button clicked");
    await p.click('.ytp-play-button');
    console.log("playing the video");
    await wait(videoDuration * 1000);

    console.log("video played");
}

async function robots(page) {
    await page.goto('https://www.youtube.com/robots.txt');

    console.log("opened yt robots");

    const cookies = await page.cookies();
    await buildCookiesTxtAsync(cookies);
    cookies.forEach(el => console.log('cookie:', el));
}

(async () => {
    try {
        const browser = await pup.launch(
            {
                // headless: true,
                // defaultViewport: null,
                args: ['--disable-blink-features=AutomationControlled', '--incognito']
            }
        );
        const p = await browser.newPage();

        await signIn(p);
        await robots(p);

        // await playVideo(p);

        await browser.close();
        console.log("All done");
    } catch (e) {
        console.error('Error:', e);
    }
})()
